// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class AdvertisingMaping
    {
        public int Id { get; set; }
        public int? AdBlockId { get; set; }
        public int? AdBlockDetailId { get; set; }
        public int? ProductTypeId { get; set; }
        public int? ProductCateC1 { get; set; }
        public int? ProductCateC2 { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string LastEditBy { get; set; }
    }
}