// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class AdvertisingBlockDetail
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public int? AdBlockId { get; set; }
        [StringLength(500)]
        public string Name { get; set; }
        public int? Qty { get; set; }
    }
}