// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class AdvertisingBlock
    {
        public AdvertisingBlock()
        {
            Advertising = new HashSet<Advertising>();
        }

        [Key]
        [Column("AdvertisingBlock_ID")]
        public int AdvertisingBlockId { get; set; }
        [Column("ArticleCategory_ID")]
        public int? ArticleCategoryId { get; set; }
        public int? Position { get; set; }
        [StringLength(500)]
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditedDate { get; set; }
        public bool? IsMobile { get; set; }
        public bool? Lock { get; set; }
        [Column("JssorSlide_ID")]
        public int? JssorSlideId { get; set; }
        public int? TimingSlide { get; set; }
        [StringLength(500)]
        public string SizeSuggest { get; set; }

        [InverseProperty("AdvertisingBlock")]
        public virtual ICollection<Advertising> Advertising { get; set; }
    }
}