// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class Advertising
    {
        [Key]
        [Column("Advertising_ID")]
        public int AdvertisingId { get; set; }
        [Column("AdvertisingBlock_ID")]
        public int? AdvertisingBlockId { get; set; }
        [StringLength(1000)]
        public string Title { get; set; }
        [StringLength(50)]
        public string Image { get; set; }
        [StringLength(50)]
        public string Ext { get; set; }
        public int? Width { get; set; }
        public int? Height { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        [Column("URL")]
        [StringLength(1000)]
        public string Url { get; set; }
        public int? Sort { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public bool? IsCode { get; set; }
        public bool? Active { get; set; }
        public int? Counter { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditDate { get; set; }
        public int? AdMostViewType { get; set; }
        public int? AdMostViewCate { get; set; }
        public int? AdMostViewChildCate { get; set; }
        public int? AdMobileType { get; set; }
        [StringLength(50)]
        public string FormId { get; set; }
        public int? ParameterId { get; set; }
        public int? CategoryId { get; set; }
        public int? ProductTypeId { get; set; }
        public int? AdBlockDetailId { get; set; }

        [ForeignKey(nameof(AdvertisingBlockId))]
        [InverseProperty("Advertising")]
        public virtual AdvertisingBlock AdvertisingBlock { get; set; }
    }
}