// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class AdvertisingBlockDetail
    {
        public int Id { get; set; }
        public int? AdBlockId { get; set; }
        public string Name { get; set; }
        public int? Qty { get; set; }
    }
}