// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class AspNetUserProfiles
    {
        [Key]
        public int Id { get; set; }
        [StringLength(128)]
        public string UserId { get; set; }
        /// <summary>
        /// 1 là email, 2 là sdt
        /// </summary>
        [StringLength(50)]
        public string RegType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RegisterDate { get; set; }
        public bool? Verified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? VerifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastActivityDate { get; set; }
        [StringLength(250)]
        public string FullName { get; set; }
        /// <summary>
        /// true là nam, false là nữ
        /// </summary>
        public bool? Gender { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BirthDate { get; set; }
        [StringLength(250)]
        public string Company { get; set; }
        [Column("ProductBrand_ID")]
        public int? ProductBrandId { get; set; }
        public int? Rank { get; set; }
        [StringLength(250)]
        public string Address { get; set; }
        [Column("Location_ID")]
        public int? LocationId { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(250)]
        public string Website { get; set; }
        [Column("FacebookID")]
        [StringLength(50)]
        public string FacebookId { get; set; }
        [StringLength(250)]
        public string Skype { get; set; }
        [StringLength(250)]
        public string AvatarUrl { get; set; }
        [StringLength(2000)]
        public string Signature { get; set; }
        public int? AccountType { get; set; }
        public int? CountryId { get; set; }
        public string ResumeProfilerContent { get; set; }
        [StringLength(500)]
        public string WorkPosition { get; set; }
        [StringLength(500)]
        public string Department { get; set; }
        [StringLength(500)]
        public string FormOfLabor { get; set; }
        [StringLength(500)]
        public string DirectManagement { get; set; }
        public string Subordinates { get; set; }
        [StringLength(250)]
        public string ReferralAccountCode { get; set; }
    }
}