// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    [Index(nameof(ProductCategoryId), nameof(ParentId), Name = "NonClusteredIndex-20190717-113259")]
    public partial class ProductCategory
    {
        [Key]
        [Column("ProductCategory_ID")]
        public int ProductCategoryId { get; set; }
        [Column("Parent_ID")]
        public int? ParentId { get; set; }
        [Column("Language_ID")]
        public int? LanguageId { get; set; }
        [StringLength(500)]
        public string Name { get; set; }
        [Column("URL")]
        [StringLength(500)]
        public string Url { get; set; }
        [StringLength(500)]
        public string Image { get; set; }
        public string Description { get; set; }
        public int? Sort { get; set; }
        public int? Counter { get; set; }
        public bool? DisplayMenu { get; set; }
        public bool? Active { get; set; }
        public bool? CanDelete { get; set; }
        [StringLength(500)]
        public string MetaTitle { get; set; }
        [StringLength(500)]
        public string MetaDescription { get; set; }
        [StringLength(500)]
        public string MetaKeywords { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditedDate { get; set; }
        public bool? HasChildren { get; set; }
        [StringLength(500)]
        public string Icon { get; set; }
    }
}