// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class ReplaceChar
    {
        public int ReplaceCharId { get; set; }
        public string OldChar { get; set; }
        public string NewChar { get; set; }
    }
}